// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPMBACKENDSELF.Data;

#nullable disable

namespace SPMBACKENDSELF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPMBACKENDSELF.Models.ProjectAllocationModel", b =>
                {
                    b.Property<int>("ProjectAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectAllocationID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("OverAllGrade")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ProjectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TotalCompletedTasks")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasksGiven")
                        .HasColumnType("int");

                    b.HasKey("ProjectAllocationID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StudentID");

                    b.ToTable("ProjectAllocation");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.ProjectMasterModel", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectID");

                    b.ToTable("projectMaster");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.TaskModel", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<decimal>("AssignedScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EarnedScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacultyRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ProgressPercentage")
                        .HasColumnType("float");

                    b.Property<int>("ProjectAllocationID")
                        .HasColumnType("int");

                    b.Property<string>("StudeStudentRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TaskAssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskPriorityID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TaskSCompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaskStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskStatusID")
                        .HasColumnType("int");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskID");

                    b.HasIndex("ProjectAllocationID");

                    b.HasIndex("TaskPriorityID");

                    b.HasIndex("TaskStatusID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.TaskPriorityModel", b =>
                {
                    b.Property<int>("TaskPriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskPriorityID"));

                    b.Property<string>("TaskPriorityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaskPriortyCssClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaskPriorityID");

                    b.ToTable("TaskPriority");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.TaskStatusModel", b =>
                {
                    b.Property<int>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskStatusID"));

                    b.Property<string>("TaskStatusCssClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaskStatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaskStatusID");

                    b.ToTable("TaskStatus");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserRoleModel", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserTypeModel", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserTypeID");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.ProjectAllocationModel", b =>
                {
                    b.HasOne("SPMBACKENDSELF.Models.UserModel", "Faculty")
                        .WithMany("FacultyProjectAllocations")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SPMBACKENDSELF.Models.ProjectMasterModel", "Project")
                        .WithMany("projectAllocations")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPMBACKENDSELF.Models.UserModel", "Student")
                        .WithMany("StudentProjectAllocations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.TaskModel", b =>
                {
                    b.HasOne("SPMBACKENDSELF.Models.ProjectAllocationModel", "ProjectAllocation")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectAllocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPMBACKENDSELF.Models.TaskPriorityModel", "taskPriority")
                        .WithMany("TaskPriorityIDs")
                        .HasForeignKey("TaskPriorityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPMBACKENDSELF.Models.TaskStatusModel", "TaskStatus")
                        .WithMany("TaskStatusIDs")
                        .HasForeignKey("TaskStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectAllocation");

                    b.Navigation("TaskStatus");

                    b.Navigation("taskPriority");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserModel", b =>
                {
                    b.HasOne("SPMBACKENDSELF.Models.UserTypeModel", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserRoleModel", b =>
                {
                    b.HasOne("SPMBACKENDSELF.Models.RoleModel", "Role")
                        .WithMany("UserRoleModels")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPMBACKENDSELF.Models.UserModel", "User")
                        .WithMany("UserRoleModels")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.ProjectAllocationModel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.ProjectMasterModel", b =>
                {
                    b.Navigation("projectAllocations");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.RoleModel", b =>
                {
                    b.Navigation("UserRoleModels");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.TaskPriorityModel", b =>
                {
                    b.Navigation("TaskPriorityIDs");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.TaskStatusModel", b =>
                {
                    b.Navigation("TaskStatusIDs");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserModel", b =>
                {
                    b.Navigation("FacultyProjectAllocations");

                    b.Navigation("StudentProjectAllocations");

                    b.Navigation("UserRoleModels");
                });

            modelBuilder.Entity("SPMBACKENDSELF.Models.UserTypeModel", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
